#!/bin/sh

cd $HOME
list="
.adobe/
.bash_logout
.cache/
.compiz-1/
.compiz-1~/
.config/
.config~/
.dbus/
.dmrc
.dosbox/
.dvdcss/
.dvdrip/
.dvdriprc
.esd_auth
.face
.fontconfig/
.gconf/
.gconf~/
.gegl-0.0/
.gimp-2.6/
.gksu.lock
.gnome2/
.gnome2~/
.gnome2_private/
.gnome2_private~/
.goutputstream-*
.gphoto/
.gstreamer-0.10/
.gtk-bookmarks
.gtkpod/
.gvfs/
.ICEauthority
.icedtea/
.kde/
.lesshst
.libreoffice/
.liferea_1.6/
.local/
.macromedia/
.miro/
.mission-control/
.monster-masher
.mplayer/
.mysql_history
.nvidia-settings-rc
.pgadmin3
.pki/
.psql_history
.pulse/
.pulse-cookie
.purple/
.rawstudio/
.shotwell/
.Skype/
.sqlite_history
.stilerrc
.sudo_as_admin_successful
.themes/
.thumbnails/
.vmware/
.Xauthority
.xsession-errors
.xsession-errors.old"

array=($list)
for i in "${array[@]}"
do
    if [ -e $i ] ; then
        echo "################################################################### $i"
        rm -rv $i
        echo
        echo
    fi
done
