#!/usr/bin/expect
set fd [open "~/.ssh/ssh-passwords" r]
set passwords_file [read -nonewline $fd]
close $fd
set passwords [split $passwords_file "\n" ]

set timeout 20
set hostname [lindex $argv 0]
set count 0
spawn ssh -t $hostname "bash -o vi -i"
expect {
  "disconnect" {
    exit
  }
  "no)?" {
    send -- "yes\r"
    exp_continue
  }
  "password:" {
    if { $count == [llength $passwords] } {
      send_user "\n\[ERROR\] Ran out of possible passwords!\n"
      exit
    }
    set pass [lindex $passwords $count]
    send -- "$pass\r"
    incr count
    exp_continue
  }
  "~" {
    send_user ":)"
  }
}
interact
