#!/bin/bash

WSL_DISTRO=Ubuntu-20.04

file=$1
shift

if [[ $file != /* ]]; then
	file="$PWD/$file"
fi

location="\\\\wsl\$\\$WSL_DISTRO${file//\//\\}"
echo "$location"

#sed -e 's#/#\\#g'

explorer.exe "$location"
