#!/bin/bash

extract () {
  local e=0
  if [ $# != 1 ];
  then
    echo
    echo "  Usage: extract [COMPRESSED_FILENAME]"
    echo
    e=1
  else
    if [ -f $1 ];
    then
      case $1 in
#        *.t@(gz|lz|xz|b@(2|z?(2))|a@(z|r?(.@(Z|bz?(2)|gz|lzma|xz)))))
#                c='bsdtar xvf' ;;
#        *.7z)   c='7z x'       ;;
#        *.Z)    c='uncompress' ;;
#        *.exe)  c='cabextract' ;;
#        *.rar)  c='unrar x'    ;;
#        *.xz)   c='unxz'       ;;
        *.tar)       tar -xvf  $1  ;;
        *.tgz)       tar -xvzf $1  ;;
        *.tar.gz)    tar -xvzf $1  ;;
        *.tbz2)      tar -xvjf $1  ;;
        *.tar.bz2)   tar -xvjf $1  ;;
        *.gz)        gunzip    $1  ;;
        *.bz2)       bunzip2   $1  ;;
        *.zip)       local dir=`echo $1 | sed -r 's,\.[^.]*$,,'`
                     mkdir $dir
                     cd $dir
                     unzip ../$1
                     cd ..
                     ;;
        *.lzma)      unlzma    $1  ;;
        *.rpm)       local dir=`echo $1 | sed -r 's,(\.[^.]*){2}$,,'`
                     mkdir $dir;
                     cd $dir;
                     rpm2cpio  ../$1 | cpio -i --make-directories
                     cd ..
                     ;;
        *)           echo "  '$1' file type unknown"; e=2 ;;
      esac
    else
      echo "  '$1' is not a regular file"
      echo
      e=3
    fi
  fi
  return $e
}

extract $1
