#!/bin/bash

#ubicaion de mi liberia de musica
Music_lib="$HOME/Music"

for arg in $@ ; do
    case "arg" in
        --debug)
            DEBUG=1
            echo W: Debug Mode!!!
            shift
            ;;
        --next)
            NEXT=1
            echo W: Next page!!!
            shift
            ;;
    esac
done

# si el usuario no pone lo que busca en la linea de comandos se lo pedimos
if [ $# -gt 0 ] ; then
    TITULO="$@"
else
    echo "Introduce el título de la canción o del artista:"
    read TITULO
fi

#Descargamos el PHP correspondiente al título.
wget http://goear.com/search.php?q="$TITULO"

#Buscamos la linea que tiene los enlaces para escuchar
grep 'href="listen' search.php?q="$TITULO" | cat > canciones.txt

if [ "$DEBUG" == 1 ] ; then
    echo W: 'TITULO'
    echo W: Print canciones.txt
    cat canciones.txt
fi

#Mediante ER, obtenemos una lista de canciones y una lista de enlaces.
egrep -o 'listen/......./[^"]*' canciones.txt > enlaces.txt
egrep -o '<a title="Escuchar[^"]*' canciones.txt > titulos.txt

function clean()
{
    rm search.php?q="$TITULO" canciones.txt enlaces.txt titulos.txt
}

#Si no encuentra nada, sale.
CONDICION=`wc -l titulos.txt | awk '{print $1}'`
if [ $CONDICION == 0 ]; then
    echo "No hay resultados. Prueba buscando otra cosa."
    clean
    exit 1
fi

NEXT=`grep 'class="next"' search.php?q="$TITULO" | grep -o 'href="[^"]*'`
#Mostramos al usuario los que ha encontrado en la primera página.
Linea=1
cat titulos.txt | while read line;
    do {
        echo $Linea: ${line:9}
        let 'Linea += 1'
    }
    done
if [ "$NEXT" ] ; then
    echo 20: NEXT
    echo $NEXT
fi

#Leemos qué canción quiere el usuario bajarse.
echo "¿Cuál te quieres bajar? Indica el número:"
read NUMERO

#Concatenamos http://www.goear.com con el enlace
GOEAR=http://www.goear.com/
LISTEN=`head -$NUMERO enlaces.txt | tail -1`
ENLACE=${GOEAR}${LISTEN}

fileid=`echo $ENLACE | cut -d '/' -f 5`
xmlurl="http://www.goear.com/tracker758.php?f="$fileid
echo xmlurl $xmlurl
infoline=`wget -qO- $xmlurl | grep ".mp3"`
mp3url=`echo $infoline | cut -d '"' -f6`
artist=`echo $infoline | cut -d '"' -f10`
title=`echo $infoline | cut -d '"' -f12`
dir="$Music_lib/$artist"
file="$artist-$title.mp3"
test -e "$dir/$file" && echo "la cancion ya existe!" && clean && exit 1
test -d "$dir" || mkdir -p "$dir" && echo se creo el directorio $dir
wget $mp3url -O "$file"
mv "$file" "$dir/"
test -e "$dir/$file" && echo la cancion esta en "$dir/$file"
clean
