#!/bin/bash
#
# Thanks to 2010 David A. Wheeler
# <http://www.dwheeler.com/essays/open-files-urls.html> and to Suraj N.
# Kurapati <https://github.com/sunaku> for his opener ruby library that pointed
# me to it.

function open(){
  os=`uname -s`
  shopt -s nocasematch
  case "$os" in
    Linux*)
      xdg-open "$@"
    ;;
    Darwin*)
      open "$@"
    ;;
    CYGWIN*)
      cygstart "$@"
    ;;
    sunos*|solaris*)
      /usr/dt/bin/sdtwebclient "$@"
    ;;
    *)
      echo Unsupported OS "$os"
    ;;
  esac
}

while test $# -gt 0 ; do
  case "$1" in
    -h|--help)
      echo TODO :S
      exit 1
    ;;
    *)
      open "$@"
      exit 0
    ;;
  esac
done
