#!/bin/bash

if [ "$#" -lt 2 ]; then
  echo
  echo "  Usage: $(basename $0) [-n|--dry-run] <source> <destination> [rsync options]"
  echo
  exit 1
fi

if [ "$(id -u)" != "0" ]; then
    sudo $0 $@;
else
    options="--verbose \
        --recursive \
        --links \
        --perms \
        --times \
        --group \
        --owner \
        --devices \
        --specials \
        --acls \
        --xattrs \
        --update \
        --del \
        --force \
        --hard-links \
        --executability \
        --human-readable \
        --progress ";
    rsync $options $src $dst $@
fi
