#!/bin/bash

if [ $# != 1 ]; then
  if [ -t 1 ] ; then
    svn diff -c `svnversion` | colordiff | less -R
  else
    svn diff -c `svnversion`
  fi
else
  if [ -t 1 ] ; then
    svn diff -c $1 | colordiff | less -R
  else
    svn diff -c $1
  fi
fi
