#!/bin/bash
echo -n 'America/Los_Angeles '
TZ='America/Los_Angeles' date
echo -n 'America/Edmonton    '
TZ='America/Edmonton' date
echo -n 'America/Costa_Rica  '
TZ='America/Costa_Rica' date
echo -n 'America/Chicago     '
TZ='America/Chicago' date
echo -n 'America/New_York    '
TZ='America/New_York' date
echo -n 'Asia/Hong_Kong      '
TZ='Asia/Hong_Kong' date

# "Additional timezones in /usr/share/zoneinfo"
echo "Remember to use date -d '<time> <timezone>' for dates in the future!"
echo "Remember to use \"TZ='America/Chicago' date\" for dates in another timezone!"
